# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Snake

# Controls when the action will run. This action runs once per day at 00:00 UTC.
on:
  schedule:
    # daily at 00:00 UTC
    - cron: "0 0 * * *"
  # This command allows us to run the Action manually from the Actions tab.
  workflow_dispatch:

# The sequence of runs in this workflow:
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Permissions needed to push to the "output" branch
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository so the job can access it
      - uses: actions/checkout@v4

      # Generates the snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: nicoKaminski
          # These lines generate the files into the "dist" folder
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # (Optional) Show the status of the working tree - helps for debugging
      - run: git status

      # Publishes only the generated files in "dist" to the "output" branch
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
